name: CI with Docker

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 17 (if necessary)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Login via Azure CLI
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Log in to Azure Container Registry (ACR)
      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: brightstraining24fall.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Build Docker image with unique tag
      - name: Build Docker image with unique tag
        env:
          VERSION_TAG: ${{ github.run_id }}  # Unique tag using GitHub run ID
        run: |
          IMAGE_NAME="brightstraining24fall.azurecr.io/bhiravina/javaapi:${VERSION_TAG}" 
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV  # Set it as an environment variable
          docker build -t $IMAGE_NAME .

      # Push Docker image to ACR
      - name: Push Docker image to ACR
        run: |
          docker push ${{ env.IMAGE_NAME }}

      # Deploy to Azure Container Instances
      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
          image: ${{ env.IMAGE_NAME }}
          registry-login-server: brightstraining24fall.azurecr.io
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: java-app
          location: 'norway east'
